sudo: required
service:
  - docker

before_install:
  - docker build -t sandrobrayen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  sandrobrayen/react-test npm run test -- --coverage

after_success:
  - docker build -t sandrobrayen/multi-client ./client
  - docker build -t sandrobrayen/multi-nginx ./nginx
  - docker build -t sandrobrayen/multi-server ./server
  - docker build -t sandrobrayen/multi-worker ./worker
  #login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push all images to docker hub
  - docker push sandrobrayen/multi-client 
  - docker push sandrobrayen/multi-nginx 
  - docker push sandrobrayen/multi-server 
  - docker push sandrobrayen/multi-worker